name: Test and Lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-action-fmt
        run: cargo install cargo-action-fmt --locked --force

      - name: Cargo check (annotated)
        shell: bash
        run: |
          set -o pipefail
          cargo check -q --message-format=json | cargo-action-fmt

      - name: Compile tests (annotated)
        shell: bash
        run: |
          set -o pipefail
          cargo test --no-run --message-format=json | cargo-action-fmt

      - name: Run tests
        run: cargo test --verbose

      - name: Check formatting
        run: cargo fmt --check

      - name: Run clippy (annotated)
        shell: bash
        run: |
          set -o pipefail
          cargo clippy -q --message-format=json -- -D warnings | cargo-action-fmt
